#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-1226"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "30f6923b23264b7bb7be290926987ecc" }
]

[assets]
directory = "./public"
